#ifndef CSTL_CSTL_ERROR_CODE_H
#define CSTL_CSTL_ERROR_CODE_H
#include "common/types/error_code.h"

#define CSTL_MODULE_ID 1

#define ERR_CSTL_EXCEED_MAX_CAPACITY MAKE_ERROR(ERR_SEV_ERROR, CSTL_MODULE_ID, COMM_ERR_TYPE_DATA, 1)  // 超越最大容量

#define ERR_CSTL_PARAM_CAPACITY_INVALID MAKE_ERROR(ERR_SEV_ERROR, CSTL_MODULE_ID, COMM_ERR_TYPE_PARAM, 1) // 入参
#define ERR_CSTL_PARAM_IDX_INVALID MAKE_ERROR(ERR_SEV_ERROR, CSTL_MODULE_ID, COMM_ERR_TYPE_PARAM, 2)
#define ERR_CSTL_PARAM_CONTAINER_EMPTY MAKE_ERROR(ERR_SEV_ERROR, CSTL_MODULE_ID, COMM_ERR_TYPE_PARAM, 3)

const char *CStl_GetErrMsg(ErrorCode errCode);

#endif  // CSTL_CSTL_ERROR_CODE_H
